BEGIN TRANSACTION;

INSERT INTO Chapter (chapter_order, chapter_name, grade, description) VALUES 
--Lớp 1
(1, N'Làm quen với một số hình', 1, ''),
(2, N'Các số đến 10', 1, ''),
(3, N'Phép cộng, phép trừ trong phạm vi 10', 1, ''),
(4, N'Các số đến 20', 1, ''),
(5, N'Các số đến 100', 1, ''),
--Lớp 2
(1, N'Ôn Tập và Bổ Sung', 2, ''),
(2, N'Phép cộng, phép trừ qua 10 trong phạm vi 20', 2, ''),
(3, N'Phép cộng, phép trừ có nhớ trong phạm vi 100', 2, ''),
(4, N'Phép Nhân, Phép Chia', 1, ''),
(5, N'Các Số Đến 1000', 1, ''),
(6, N'Phép Cộng, Phép Trừ Trong Phạm Vi 1000', 1, ''),
--Lớp 3
(1, N'Ôn tập và bổ sung', 3, ''),
(2, N'Phép Nhân, Phép Chia trong Phạm Vi 1000', 3, ''),
(3, N'Các Số Đến 10,000', 3, ''),
(4, N'Các Số Đến 100,000', 3, ''),
--Lớp 4
(1, N'Ôn Tập và Bổ Sung', 4, ''),
(2, N'Số tự nhiên', 4, ''),
(3, N'Các Phép Tính với Số Tự Nhiên', 4, ''),
(4, N'Phân Số', 4, ''),
--Lớp 5
(1, N'Ôn Tập và Bổ Sung', 5, ''),
(2, N'Số Thập Phân', 5, ''),
(3, N'Hình Tam Giác, Hình Thang, Hình Tròn', 5, ''),
(4, N'Ôn Tập Học Kì 1', 5, ''),
(5, N'Tỉ Số Phần Trăm', 5, ''),
(6, N'Hình Hộp Chữ Nhật, Hình Lập Phương, Hình Trụ', 5, ''),
(7, N'Số Đo Thời Gian, Vận Tốc, Quãng Đường, Thời Gian', 5, ''),
(8, N'Ôn Tập Cuối Năm', 5, '');

INSERT INTO Lesson (lesson_order, lesson_name, chapter_id, lesson_content) VALUES
--Lớp 1
----Chương 1
(1, N'Vị trí', 1, ''),
(2, N'Khối hộp chữ nhật - Khối lập phương', 1, ''),
(3, N'Hình tròn - Hình tam giác - Hình vuông - Hình chữ nhật', 1, ''),
(4, N'Xếp hình', 1, ''),
(5, N'Thực hành và trải nghiệm: Vui Trung thu', 1, ''),
----Chương 2
(1, N'Các số 1, 2, 3', 2, ''),
(2, N'Các số 4, 5', 2, ''),
(3, N'Tách - Gộp số', 2, ''),
(4, N'Bằng nhau, nhiều hơn, ít hơn', 2, ''),
(5, N'So sánh các số: bằng, lớn hơn, bé hơn', 2, ''),
(6, N'Các dấu =, >, <', 2, ''),
(7, N'Số 6', 2, ''),
(8, N'Số 7', 2, ''),
(9, N'Số 8', 2, ''),
(10, N'Số 9', 2, ''),
(11, N'Số 0', 2, ''),
(12, N'Số 10', 2, ''),
(13, N'Em làm được những gì?', 2, ''),
(14, N'Thực hành và trải nghiệm: Sông nước miền Tây', 2, ''),
----Chương 3
(1, N'Phép cộng', 3, ''),
(2, N'Phép cộng trong phạm vi 10', 3, ''),
(3, N'Cộng bằng cách đếm thêm', 3, ''),
(4, N'Phép trừ', 3, ''),
(5, N'Phép trừ trong phạm vi 10', 3, ''),
(6, N'Trừ bằng cách đếm bớt', 3, ''),
(7, N'Em làm được những gì?', 3, ''),
(8, N'Ôn tập học kỳ 1', 3, ''),
(9, N'Thực hành và trải nghiệm: Em đi bộ theo luật giao thông', 3, ''),
----Chương 4
(1, N'Các số đến 20', 4, ''),
(2, N'Các phép tính dạng 10 + 4, 14 - 4', 4, ''),
(3, N'Các phép tính dạng 12 + 3, 15 - 3', 4, ''),
(4, N'Chiếc đồng hồ của em', 4, ''),
(5, N'Em làm được những gì?', 4, ''),
----Chương 5
(1, N'Chục - Số tròn chục', 5, ''),
(2, N'Các phép tính dạng 30 + 20, 50 - 20', 5, ''),
(3, N'Chục - Đơn vị', 5, ''),
(4, N'Các số đến 40', 5, ''),
(5, N'So sánh các số', 5, ''),
(6, N'Các số đến 100', 5, ''),
(7, N'Bảng các số từ 1 đến 100', 5, ''),
(8, N'Các phép tính dạng 34 + 23, 57 - 23', 5, ''),
(9, N'Em làm được những gì?', 5, ''),
(10, N'Các ngày trong tuần', 5, ''),
(11, N'Tờ lịch của em', 5, ''),
(12, N'Thực hành và trải nghiệm: Em và các bạn', 5, ''),
(13, N'Độ dài',5,''),
(14, N'Đo độ dài', 5, ''),
(15, N'Xăng-ti-mét. Đơn vị đo độ dài', 5, ''),
(16, N'Em làm được những gì?', 5, ''),
(17, N'Ôn tập cuối năm', 5, ''),
(18, N'Thực hành và trải nghiệm: Ong và hoa', 5, ''),
(19, N'Bảng từ ngữ.', 5, ''),
--Lớp 2
----Chương 1
(1, N'Ôn tập các số đến 100', 1, ''),
(2, N'Ước lượng', 1, ''),
(3, N'Số hạng - Tổng', 1, ''),
(4, N'Số bị trừ - Số trừ - Hiệu', 1, ''),
(5, N'Nhiều hơn hay ít hơn bao nhiêu', 1, ''),
(6, N'Em làm được những gì?', 1, ''),
(7, N'Điểm - Đoạn thẳng', 1, ''),
(8, N'Tia số - Số liên trước, số liền sau', 1, ''),
(9, N'Đề-xi-mét', 1, ''),
(10, N'Em làm được những gì?', 1, ''),
(11, N'Thực hành và trải nghiệm: Tìm hiểu về chiều cao của cây ở trường em', 1, ''),
----Chương 2
(1, N'Phép cộng có tổng bằng 10', 2, ''),
(2, N'9 cộng với một số', 2, ''),
(3, N'8 cộng với một số', 2, ''),
(4, N'7 cộng với một số, 6 cộng với một số', 2, ''),
(5, N'Bảng cộng', 2, ''),
(6, N'Đường thẳng - Đường cong', 2, ''),
(7, N'Đường gấp khúc', 2, ''),
(8, N'Ba điểm thẳng hàng', 2, ''),
(9, N'Em làm được những gì?', 2, ''),
(10, N'Phép trừ có hiệu bằng 10', 2, ''),
(11, N'11 trừ đi một số', 2, ''),
(12, N'12 trừ đi một số', 2, ''),
(13, N'13 trừ đi một số', 2, ''),
(14, N'14, 15, 16, 17, 18 trừ đi một số', 2, ''),
(15, N'Bảng trừ', 2, ''),
(16, N'Em giải bài toán', 2, ''),
(17, N'Bài toán nhiều hơn', 2, ''),
(18, N'Bài toán ít hơn', 2, ''),
(19, N'Đựng nhiều nước, đựng ít nước', 2, ''),
(20, N'Lít', 2, ''),
(21, N'Em làm được những gì?', 2, ''),
(22, N'Thực hành và trải nghiệm: Chơi cắm cờ', 2, ''),
----Chương 3
(1, N'Phép cộng có tổng là số tròn chục', 3, ''),
(2, N'Phép cộng có nhớ trong phạm vi 100', 3, ''),
(3, N'Em làm được những gì?', 3, ''),
(4, N'Phép trừ có số bị trừ là số tròn chục', 3, ''),
(5, N'Phép trừ có nhớ trong phạm vi 100', 3, ''),
(6, N'Em làm được những gì?', 3, ''),
(7, N'Thu thập, phân loại, kiểm đếm', 3, ''),
(8, N'Biểu đồ tranh', 3, ''),
(9, N'Có thể, chắc chắn, không thể', 3, ''),
(10, N'Ngày, giờ', 3, ''),
(11, N'Ngày, tháng', 3, ''),
(12, N'Em làm được những gì?', 3, ''),
----Chương 4
(1, N'Tổng các số hạng bằng nhau', 4, ''),
(2, N'Phép nhân', 4, ''),
(3, N'Thừa số - Tích', 4, ''),
(4, N'Bảng nhân 2', 4, ''),
(5, N'Bảng nhân 5', 4, ''),
(6, N'Phép chia', 4, ''),
(7, N'Số bị chia – Số chia – Thương', 4, ''),
(8, N'Bảng chia 2', 4, ''),
(9, N'Bảng chia 5', 4, ''),
(10, N'Giờ, phút, xem đồng hồ', 4, ''),
(11, N'Em làm được những gì?', 4, ''),
(12, N'Thực hành và trải nghiệm: Bạn đến nơi nào?', 4, ''),
----Chương 5
(1, N'Đơn vị, chục, trăm, nghìn', 5, ''),
(2, N'Các số từ 101 đến 110', 5, ''),
(3, N'Các số từ 111 đến 200', 5, ''),
(4, N'Các số có ba chữ số', 5, ''),
(5, N'Viết số thành tổng các trăm, chục, đơn vị', 5, ''),
(6, N'So sánh các số có ba chữ số', 5, ''),
(7, N'Em làm được những gì?', 5, ''),
(8, N'Mét', 5, ''),
(9, N'Ki-lô-mét', 5, ''),
(10, N'Khối trụ - Khối cầu', 5, ''),
(11, N'Hình tứ giác', 5, ''),
(12, N'Xếp hình, gấp hình', 5, ''),
(13, N'Em làm được những gì?', 5, ''),
(14, N'Thực hành và trải nghiệm: Đo bằng gang tay để biết vật dài bao nhiêu mét', 5, ''),
----Chương 6
(1, N'Phép cộng không nhớ trong phạm vi 1000', 6, ''),
(2, N'Phép trừ không nhớ trong phạm vi 1000', 6, ''),
(3, N'Nặng hơn, nhẹ hơn', 6, ''),
(4, N'Ki-lô-gam', 6, ''),
(5, N'Phép cộng có nhớ trong phạm vi 1000', 6, ''),
(6, N'Phép trừ có nhớ trong phạm vi 1000', 6, ''),
(7, N'Tiền Việt Nam', 6, ''),
(8, N'Em làm được những gì?', 6, ''),
--Lớp 3
----Chương 1
(1, N'Ôn tập các số đến 1000', 1, ''),
(2, N'Ôn tập phép cộng, phép trừ', 1, ''),
(3, N'Cộng nhẩm, trừ nhẩm', 1, ''),
(4, N'Tìm số hạng', 1, ''),
(5, N'Tìm số bị trừ, tìm số trừ', 1, ''),
(6, N'Ôn tập phép nhân', 1, ''),
(7, N'Ôn tập phép chia', 1, ''),
(8, N'Tìm thừa số', 1, ''),
(9, N'Tìm số bị chia, tìm số chia', 1, ''),
(10, N'Em làm được những gì?', 1, ''),
(11, N'Mi-li-mét', 1, ''),
(12, N'Hình tam giác, Hình tứ giác', 1, ''),
(13, N'Khối hợp chữ nhật, Khối lập phương', 1, ''),
(14, N'Xếp hình', 1, ''),
(15, N'Xem đồng hồ', 1, ''),
(16, N'Bài toán giải bằng hai bước tính', 1, ''),
(17, N'Làm quen với biểu thức', 1, ''),
(18, N'Tính giá trị của biểu thức', 1, ''),
(19, N'Tính giá trị của biểu thức (tiếp theo)', 1, ''),
(20, N'Tính giá trị của biểu thức (tiếp theo)', 1, ''),
(21, N'Làm tròn số', 1, ''),
(22, N'Làm quen với chữ số La Mã', 1, ''),
(23, N'Em làm được những gì?', 1, ''),
(24, N'Thực hành và trải nghiệm: Làm hộp bút từ vỏ hộp đã qua sử dụng', 1, ''),
----Chương 2
(1, N'Bảng nhân 3', 2, ''),
(2, N'Bảng chia 3', 2, ''),
(3, N'Bảng nhân 4', 2, ''),
(4, N'Bảng chia 4', 2, ''),
(5, N'Một phần hai, một phần ba, một phần tư, một phần năm', 2, ''),
(6, N'Nhân nhẩm, chia nhẩm', 2, ''),
(7, N'Em làm được những gì?', 2, ''),
(8, N'Nhân với số có một chữ số trong phạm vi 1000', 2, ''),
(9, N'Nhân với số có một chữ số trong phạm vi 1000 (tiếp theo)', 2, ''),
(10, N'Phép chia hết và phép chia có dư', 2, ''),
(11, N'Chia số có hai chữ số cho số có một chữ số', 2, ''),
(12, N'Em làm được những gì?', 2, ''),
(13, N'Bảng nhân 6', 2, ''),
(14, N'Bảng chia 6', 2, ''),
(15, N'Gấp một số lên một số lần', 2, ''),
(16, N'Bảng nhân 7', 2, ''),
(17, N'Bảng chia 7', 2, ''),
(18, N'Bảng nhân 8', 2, ''),
(19, N'Bảng chia 8', 2, ''),
(20, N'Giảm một số đi một số lần', 2, ''),
(21, N'Bảng nhân 9', 2, ''),
(22, N'Bảng chia 9', 2, ''),
(23, N'Em làm được những gì?', 2, ''),
(24, N'Xem đồng hồ', 2, ''),
(25, N'Chia số có ba chữ số cho số có một chữ số', 2, ''),
(26, N'So sánh số lớn gấp mấy lần số bé', 2, ''),
(27, N'Điểm ở giữa. Trung điểm của đoạn thẳng', 2, ''),
(28, N'Hình tròn', 2, ''),
(29, N'Nhiệt độ. Đo nhiệt độ', 2, ''),
(30, N'Em làm được những gì?', 2, ''),
(31, N'Thực hành và trải nghiệm: Giờ giấc – Thời tiết', 2, ''),
----Chương 3
(1, N'Chục nghìn', 3, ''),
(2, N'Các số có bốn chữ số', 3, ''),
(3, N'So sánh các số có bốn chữ số', 3, ''),
(4, N'Phép cộng các số trong phạm vi 10,000', 3, ''),
(5, N'Phép trừ các số trong phạm vi 10,000', 3, ''),
(6, N'Em làm được những gì?', 3, ''),
(7, N'Tháng, năm', 3, ''),
(8, N'Gam', 3, ''),
(9, N'Mi-li-lít', 3, ''),
(10, N'Nhân số có bốn chữ số với số có một chữ số', 3, ''),
(11, N'Chia số có bốn chữ số cho số có một chữ số', 3, ''),
(12, N'Em làm được những gì?', 3, ''),
(13, N'Góc vuông, góc không vuông', 3, ''),
(14, N'Hình chữ nhật', 3, ''),
(15, N'Hình vuông', 3, ''),
(16, N'Chu vi hình tam giác, chu vi hình tứ giác', 3, ''),
(17, N'Chu vi hình chữ nhật', 3, ''),
(18, N'Chu vi hình vuông', 3, ''),
(19, N'Bảng thống kê số liệu', 3, ''),
(20, N'Các khả năng xảy ra của một sự kiện', 3, ''),
(21, N'Em làm được những gì?', 3, ''),
(22, N'Thực hành và trải nghiệm: Tính chu vi sàn phòng học, chu vi sân trường', 3, ''),
----Chương 4
(1, N'Trăm nghìn', 4, ''),
(2, N'Các số có năm chữ số', 4, ''),
(3, N'So sánh các số có năm chữ số', 4, ''),
(4, N'Phép cộng các số trong phạm vi 100,000', 4, ''),
(5, N'Phép trừ các số trong phạm vi 100,000', 4, ''),
(6, N'Em làm được những gì?', 4, ''),
(7, N'Nhân số có năm chữ số với số có một chữ số', 4, ''),
(8, N'Chia số có năm chữ số cho số có một chữ số', 4, ''),
(9, N'Em làm được những gì?', 4, ''),
(10, N'Diện tích của một hình', 4, ''),
(11, N'Xăng-ti-mét vuông', 4, ''),
(12, N'Diện tích hình chữ nhật', 4, ''),
(13, N'Diện tích hình vuông', 4, ''),
(14, N'Tiền Việt Nam', 4, ''),
--Lớp 4
----Chương 1
(1, N'Ôn tập các số đến 100000', 1, ''),
(2, N'Ôn tập phép cộng, phép trừ', 1, ''),
(3, N'Ôn tập phép nhân, phép chia', 1, ''),
(4, N'Số chẵn, số lẻ', 1, ''),
(5, N'Em làm được những gì?', 1, ''),
(6, N'Bài toán liên quan đến rút về đơn vị', 1, ''),
(7, N'Bài toán liên quan đến rút về đơn vị (tiếp theo)', 1, ''),
(8, N'Bài toán giải bằng ba bước tính', 1, ''),
(9, N'Ôn tập biểu thức số', 1, ''),
(10, N'Biểu thức có chứa chữ', 1, ''),
(11, N'Biểu thức có chứa chữ (tiếp theo)', 1, ''),
(12, N'Biểu thức có chứa chữ (tiếp theo)', 1, ''),
(13, N'Tính chất giao hoán, tính chất kết hợp của phép cộng', 1, ''),
(14, N'Tính chất giao hoán, tính chất kết hợp của phép nhân', 1, ''),
(15, N'Em làm được những gì?', 1, ''),
(16, N'Dãy số liệu', 1, ''),
(17, N'Biểu đồ cột', 1, ''),
(18, N'Số lần lặp lại của một sự kiện', 1, ''),
(19, N'Tìm số trung bình cộng', 1, ''),
(20, N'Đề-xi-mét vuông', 1, ''),
(21, N'Mét vuông', 1, ''),
(22, N'Em làm được những gì?', 1, ''),
(23, N'Thực hành và trải nghiệm', 1, ''),
----Chương 2
(1, N'Các số có sáu chữ số - Hàng và lớp', 2, ''),
(2, N'Triệu - Lớp triệu', 2, ''),
(3, N'Đọc, viết các số tự nhiên trong hệ thập phân', 2, ''),
(4, N'So sánh và xếp thứ tự các số tự nhiên', 2, ''),
(5, N'Dãy số tự nhiên', 2, ''),
(6, N'Em làm được những gì?', 2, ''),
(7, N'Đo góc - Góc nhọn, góc tù, góc bẹt', 2, ''),
(8, N'Hai đường thẳng vuông góc', 2, ''),
(9, N'Hai đường thẳng song song', 2, ''),
(10, N'Em làm được những gì?', 2, ''),
(11, N'Giây', 2, ''),
(12, N'Thể kỉ', 2, ''),
(13, N'Yến, tạ, tấn', 2, ''),
(14, N'Em làm được những gì?', 2, ''),
(15, N'Ôn tập học kì 1', 2, ''),
(16, N'Thực hành và trải nghiệm', 2, ''),
----Chương 3
(1, N'Phép cộng các số tự nhiên', 3, ''),
(2, N'Phép trừ các số tự nhiên', 3, ''),
(3, N'Tìm hai số khi biết tổng và hiệu của hai số đó', 3, ''),
(4, N'Em làm được những gì?', 3, ''),
(5, N'Nhân với 10, 100, 1000, ... Chia cho 10, 100, 1000', 3, ''),
(6, N'Nhân các số có tận cùng là chữ số 0', 3, ''),
(7, N'Nhân với số có hai chữ số', 3, ''),
(8, N'Em làm được những gì?', 3, ''),
(9, N'Chia hai số có tận cùng là chữ số 0', 3, ''),
(10, N'Uớc lượng thương trong phép chia', 3, ''),
(11, N'Chia cho số có hai chữ số', 3, ''),
(12, N'Em làm được những gì?', 3, ''),
(13, N'Hình bình hành', 3, ''),
(14, N'Hình thoi', 3, ''),
(15, N'Xếp hình, vẽ hình', 3, ''),
(16, N'Mi-li-mét vuông', 3, ''),
(17, N'Em làm được những gì?', 3, ''),
(18, N'Thực hành và trải nghiệm', 3, ''),
----Chương 4
(1, N'Phân số', 4, ''),
(2, N'Phân số và phép chia số tự nhiên', 4, ''),
(3, N'Phân số bằng nhau', 4, ''),
(4, N'Rút gọn phân số', 4, ''),
(5, N'Em làm được những gì?', 4, ''),
(6, N'Quy đồng mẫu số các phân số', 4, ''),
(7, N'So sánh hai phân số', 4, ''),
(8, N'Em làm được những gì?', 4, ''),
(9, N'Cộng hai phân số cùng mẫu số', 4, ''),
(10, N'Cộng hai phân số khác mẫu số', 4, ''),
(11, N'Em làm được những gì?', 4, ''),
(12, N'Trừ hai phân số cùng mẫu số', 4, ''),
(13, N'Trừ hai phân số khác mẫu số', 4, ''),
(14, N'Em làm được những gì?', 4, ''),
(15, N'Phép nhân phân số', 4, ''),
(16, N'Phép chia phân số', 4, ''),
(17, N'Tìm phân số của một số', 4, ''),
(18, N'Em làm được những gì?', 4, ''),
(19, N'Ôn tập cuối năm', 4, ''),
(20, N'Thực hành và trải nghiệm', 4, ''),
--Lớp 5
----Chương 1
(1, N'Ôn tập số tự nhiên và các phép tính', 1, ''),
(2, N'Ôn tập phân số', 1, ''),
(3, N'Ôn tập và bổ sung các phép tính với phân số', 1, ''),
(4, N'Phân số thập phân', 1, ''),
(5, N'Tỉ số', 1, ''),
(6, N'Tỉ số của số lần lặp lại một sự kiện so với tổng số lần thực hiện', 1, ''),
(7, N'Em làm được những gì?', 1, ''),
(8, N'Ôn tập và bổ sung bài toán liên quan đến rút về đơn vị', 1, ''),
(9, N'Bài toán giải bằng bốn bước tính', 1, ''),
(10, N'Tìm hai số khi biết tổng và tỉ số của hai số đó', 1, ''),
(11, N'Tìm hai số khi biết hiệu và tỉ số của hai số đó', 1, ''),
(12, N'Em làm được những gì?', 1, ''),
(13, N'Héc-ta', 1, ''),
(14, N'Ki-lô-mét vuông', 1, ''),
(15, N'Tỉ lệ bản đồ', 1, ''),
(16, N'Em làm được những gì?', 1, ''),
(17, N'Thực hành và trải nghiệm', 1, ''),
----Chương 2
(1, N'Số thập phân', 2, ''),
(2, N'Hàng của số thập phân. Đọc, viết số thập phân', 2, ''),
(3, N'Số thập phân bằng nhau', 2, ''),
(4, N'So sánh hai số thập phân', 2, ''),
(5, N'Làm tròn số thập phân', 2, ''),
(6, N'Em làm được những gì?', 2, ''),
(7, N'Viết các số đo độ dài dưới dạng số thập phân', 2, ''),
(8, N'Viết các số đo khối lượng dưới dạng số thập phân', 2, ''),
(9, N'Viết các số đo diện tích dưới dạng số thập phân', 2, ''),
(10, N'Em làm được những gì?', 2, ''),
(11, N'Cộng hai số thập phân', 2, ''),
(12, N'Trừ hai số thập phân', 2, ''),
(13, N'Em làm được những gì', 2, ''),
(14, N'Nhân một số thập phân với một số tự nhiên', 2, ''),
(15, N'Nhân hai số thập phân', 2, ''),
(16, N'Nhân một số thập phân với 10; 100; 1000; Nhân một số thập phân với 0,1; 0,01; 0,001', 2, ''),
(17, N'Em làm được những gì?', 2, ''),
(18, N'Chia một số thập phân cho một số tự nhiên', 2, ''),
(19, N'Chia một số tự nhiên cho một số tự nhiên mà thương là một số thập phân', 2, ''),
(20, N'Chia một số thập phân với 10; 100; 1000; Chia một số thập phân với 0,1; 0,01; 0,001', 2, ''),
(21, N'Em làm được những gì?', 2, ''),
(22, N'Chia một số tự nhiên cho một số thập phân', 2, ''),
(23, N'Chia một số thập phân cho một số thập phân', 2, ''),
(24, N'Em làm được những gì?', 2, ''),
(25, N'Thực hành và trải nghiệm', 2, ''),
----Chương 3
(1, N'Hình tam giác', 3, ''),
(2, N'Diện tích hình tam giác', 3, ''),
(3, N'Hình thang', 3, ''),
(4, N'Diện tích hình thang', 3, ''),
(5, N'Đường tròn, hình tròn', 3, ''),
(6, N'Chu vi hình tròn', 3, ''),
(7, N'Diện tích hình tròn', 3, ''),
(8, N'Em làm được những gì?', 3, ''),
(9, N'Thực hành và trải nghiệm', 3, ''),
----Chương 4
(1, N'Ôn tập số thập phân', 4, ''),
(2, N'Ôn tập các phép tính với số thập phân', 4, ''),
(3, N'Ôn tập hình học và đo lường', 4, ''),
(4, N'Ôn tập một số yếu tố thống kê và xác suất', 4, ''),
----Chương 5
(1, N'Tỉ số phần trăm', 5, ''),
(2, N'Tính tỉ số phần trăm của hai số', 5, ''),
(3, N'Tìm giá trị phần trăm của một số', 5, ''),
(4, N'Em làm được những gì?', 5, ''),
(5, N'Sử dụng máy tính cầm tay', 5, ''),
(6, N'Viết các số liệu dưới dạng tỉ số phần trăm', 5, ''),
(7, N'Biểu đồ hình quạt tròn', 5, ''),
(8, N'Em làm được những gì?', 5, ''),
----Chương 6
(1, N'Hình hộp chữ nhật, hình lập phương', 6, ''),
(2, N'Diện tích xung quanh và diện tích toàn phần của hình hộp chữ nhật', 6, ''),
(3, N'Diện tích xung quanh và diện tích toàn phần của hình lập phương', 6, ''),
(4, N'Hình trụ', 6, ''),
(5, N'Em làm được những gì?', 6, ''),
(6, N'Thể tích của một hình', 6, ''),
(7, N'Xăng-ti-mét khối', 6, ''),
(8, N'Đề-xi-mét khối', 6, ''),
(9, N'Mét khối', 6, ''),
(10, N'Thể tích hình hộp chữ nhật', 6, ''),
(11, N'Thể tích hình lập phương', 6, ''),
(12, N'Em làm được những gì?', 6, ''),
(13, N'Thực hành và trải nghiệm', 6, ''),
----Chương 7
(1, N'Các đơn vị đo thời gian', 7, ''),
(2, N'Cộng số đo thời gian', 7, ''),
(3, N'Trừ số đo thời gian', 7, ''),
(4, N'Nhân số đo thời gian', 7, ''),
(5, N'Chia số đo thời gian', 7, ''),
(6, N'Em làm được những gì?', 7, ''),
(7, N'Vận tốc', 7, ''),
(8, N'Quãng đường', 7, ''),
(9, N'Thời gian', 7, ''),
(10, N'Em làm được những gì?', 7, ''),
----Chương 8
(1, N'Ôn tập số tự nhiên', 8, ''),
(2, N'Ôn tập phân số', 8, ''),
(3, N'Ôn tập số thập phân', 8, ''),
(4, N'Ôn tập phép cộng, phép trừ', 8, ''),
(5, N'Ôn tập phép cộng, phép trừ (tiếp theo)', 8, ''),
(6, N'Ôn tập phép nhân, phép chia', 8, ''),
(7, N'Ôn tập phép nhân, phép chia (tiếp theo)', 8, ''),
(8, N'Ôn tập hình phẳng và hình khối', 8, ''),
(9, N'Ôn tập độ dài, khối lượng, dung tích, nhiệt độ, tiền Việt Nam', 8, ''),
(10, N'Ôn tập chu vi, diện tích, thể tích', 8, ''),
(11, N'Ôn tập chu vi, diện tích, thể tích (tiếp theo)', 8, ''),
(12, N'Ôn tập số đo thời gian, vận tốc, quãng đường, thời gian', 8, ''),
(13, N'Ôn tập số đo thời gian, vận tốc, quãng đường, thời gian (tiếp theo)', 8, ''),
(14, N'Ôn tập một số yếu tố xác suất', 8, ''),
(15, N'Ôn tập một số yếu tố thống kê', 8, ''),
(16, N'Thực hành và trải nghiệm', 8, '');	

COMMIT;

SELECT * FROM Chapter
SELECT * FROM Lesson


